### ISSUE TITLE
Investigate public folder accessibility

### ISSUE THREAD

**Issue by davidbuckhurst** [bbc/hive-scheduler#100]
Just re-ran the test to get some fresh logs
I get this: E 2016-03-23 14:36:27: Error uploading artifact executed_script.sh: 795: unexpected token at
followed by a bunch of html
This looks like the most important part of it
This message was deleted
<header>
<h1>
Errno::EACCES
in Api::ArtifactsController#create
</h1>
</header>
<div id="container">
<h2>Permission denied @ dir_s_mkdir - public</h2>
<div class="source">
<div class="info">

maikeru 13:43
For some reason it gitter didn't like it when I tried to format it nicely

jrmhaig 13:54
Does the user running the scheduler have write access to the public directory?

maikeru 13:55
If you mean ./public under the hive-scheduler working directory then yes.
I've done everything with the same (non-root) user (git clone, bundle install, rails etc)
Would it be anything to do with this? http://stackoverflow.com/questions/11864175/paperclip-errnoeacces-permission-denied-system
I.e. are we trying to right to /public instead of ./public for some reason?
Looking in hive-scheduler/app/models/artifact.rb
I see this line
has_attached_file :asset, path: "#{Chamber.env.attachment.path_base}/artifacts/:id/:filename", url: "/artifacts/:id/:filename"
I wonder if we need to add something like :rails_root in the front of the path

jrmhaig 14:00
What do you have in your configuration file for attachement/path_base?

davidbuckhurst 14:00
What is set for the dev environment?

maikeru 14:01
attachment:
storage: filesystem
s3_bucket:
path_base: public
Ah, gitter lost the whitespace
That's the same for both development and production (which just uses default)

maikeru 14:34
I changed path_base to /home/hive/hive-scheduler/public and that worked

davidbuckhurst 15:09
That's a strange one -- I don't get that behaviour at all
I'll copy this conversation into a ticket so we can properly investigate it

**Comment by jonpwilson** [comment]
I can't seem to recreate this issue, I've tried changing the path_base: to 'public' and it works correctly for uploading both assets and results:

```
Started POST "/api/jobs/5/artifacts" for 127.0.0.1 at 2016-10-03 14:14:28 +0100
Processing by Api::ArtifactsController#create as JSON
  Parameters: {"data"=>#<ActionDispatch::Http::UploadedFile:0x007faac1e48338 @tempfile=#<Tempfile:/var/folders/8j/r0912xkn32s2w6l_wk1btgls270144/T/RackMultipart20161003-33835-1jecpo>, @original_filename="stdout.log", @content_type="text/x-log", @headers="Content-Disposition: form-data; name=\"data\"; filename=\"stdout.log\"\r\nContent-Length: 1699\r\nContent-Type: text/x-log\r\nContent-Transfer-Encoding: binary\r\n">, "job_id"=>"5"}
  Job Load (0.1ms)  SELECT  "jobs".* FROM "jobs"  WHERE "jobs"."id" = ? LIMIT 1  [["id", 5]]
   (0.2ms)  begin transaction
  SQL (0.3ms)  INSERT INTO "artifacts" ("asset_content_type", "asset_file_name", "asset_file_size", "asset_updated_at", "created_at", "job_id", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?)  [["asset_content_type", "text/x-log"], ["asset_file_name", "stdout.log"], ["asset_file_size", 1699], ["asset_updated_at", "2016-10-03 13:14:28.727758"], ["created_at", "2016-10-03 13:14:28.729500"], ["job_id", 5], ["updated_at", "2016-10-03 13:14:28.729500"]]
   (0.7ms)  commit transaction
Completed 200 OK in 11ms (Views: 0.3ms | ActiveRecord: 1.3ms)
```

```
cat config/settings.yml | grep -A14 'development:'
development:
  <<: *defaults
  database:
    adapter: sqlite3
    database: db/test_database.sql
  better_errors_for_all: true
  hive_mind:
    url: http://localhost:3001
  testmite:
    url: http://localhost:3002
  attachment:
    storage: filesystem
    s3_bucket:
    path_base: public
```

It may be that, on certain systems,  relative paths don't work as expected so I tried this on one of the Ubuntu Servers (14.04) and it worked as expected.

I'm going to close this ticket as it's not been reported again within the last 6 months but if it's still an issue, please feel free to re-open and provide more information.

Thanks
