### ISSUE TITLE
Hive load time

### ISSUE THREAD

**Issue by brownj45** [bbc/hive-scheduler#133]
The load time to access the hive is over 50 seconds, could this be reduced? we (MCE) are using the hive-jenkins plugin as part of the pipeline process and more often than not our builds are failing due to hive timeouts.

**Comment by jonpwilson** [comment]
I've added some indices to a couple of tables (see PR #134) which has improved the speed for polling devices, but the main issue seems to be with the 'Latest Result' summary that only occurs when you access the non-API version of the site.

Jenna, what calls are you making? Are you using the API routes?

Thanks

**Comment by brownj45** [comment]
we are using https://github.com/bbc/hive-trigger/blob/master/bin/hive-batch-poll script to access the hive which uses a base url including the API route. By making the timeout of the curl command 60 seconds it seems to have worked around the problem, if you've made some improvements I could try to remove the 60 second default and see if this problem still exists?

**Comment by jonpwilson** [comment]
Please do

**Comment by jonpwilson** [comment]
Given it's been a month since the fix and we've not heard of any more issues (and tests are running reliably), I'm closing this. Please feel free to create a new issue if this is still a problem
