### ISSUE TITLE
"Jobs group is invalid" when not entering all mandatory fields

### ISSUE THREAD

**Issue by jonpwilson** [bbc/hive-scheduler#22]
When creating a new batch, if you don't enter all of the mandatory fields (i.e. Version) then you receive the following error message:

<img width="205" alt="screen shot 2015-09-03 at 09 46 12" src="https://cloud.githubusercontent.com/assets/6515084/9654166/de9464a6-5220-11e5-8360-f1be72c6e59f.png">

But 'Job groups' isn't a valid field nor is it mandatory - in this example entering a version is enough to pass the validation.

**Comment by jrmhaig** [comment]
Is this still an issue?

**Comment by jonpwilson** [comment]
Yes
<img width="1175" alt="screen shot 2016-02-09 at 09 48 50" src="https://cloud.githubusercontent.com/assets/6515084/12912759/91ab4348-cf12-11e5-8a28-dfbd6fcab384.png">
