### ISSUE TITLE
Unable to delete any items from the queue or feature list for a device on DeviceDB 

### ISSUE THREAD

**Issue by jitgo** [bbc/hive-scheduler#81]
steps
1] Select to edit a device
2] Delete a queue or feature item
3] Save
4] Refresh page and edit item again

Issue:
The item you deleted earlier has now re-appeared.

**Comment by Asimk21** [comment]
Workaround: Delete the device from DeviceDB and restart the hive.

**Comment by Asimk21** [comment]
Moved here https://github.com/bbc/devicedb/issues/217
